fragment BrowseTracks on Query {
  learn {
    tracks {
      items {
        name
        description
        previewProjects {
          name
          media {
            image
          }
        }
        difficulty {
          name
          hexCodeColor
        }
      }
    }
  }
}

query BrowseTracksQuery {
  ...BrowseTracks
}